language: node_js
os: 
  - linux
  - osx
  - windows 
sudo: false
node_js:
  - "4"
  - "6"
  - "8"
  - "10"
  - "12"
after_success:
  - bash <(curl -s https://codecov.io/bash) -e TRAVIS_NODE_VERSION
install:
  - npm install
  - npm install -g codecov
script:
  - npm test
  - codecov
