language: node_js
os: 
  - linux
  - osx
  - windows 
sudo: false
node_js:
  - "4"
  - "6"
  - "8"
  - "10"
  - "12"
install:
  - npm install
  - npm install codecov
script:
  - npm test
  - ./node_modules/.bin/codecov
