language: node_js
os: 
  - windows
  - linux
  - osx
sudo: true
node_js:
  - "4"
  - "6"
  - "8"
  - "10"
  - "12"
env:
  - NODE_ENV=test
install:
  - npm install
  - npm install -g codecov
  - npm install -g nyc
  - npm install -g mocha
script:
  - npm run test_travis
  - codecov --root .. --no-color --disable gcov -f .nyc_output -t 8026a7f2-5eb0-487c-9510-d2c7469eac5d